### ISSUE TITLE
How to determine wich report user is requested

### ISSUE THREAD

**Issue by adopilot** [microsoft/Reporting-Services#145]
Flowing instruction here on web I managed to start debugging security extension on  SSRS2017.

Before I start implementing my own logic, I am wondering , is there a way to implement security per folder / report.

When I attach visual studio debugger,VS hit break point at CheckAccess methods.
Bud I do always get null for secDesc parameter.
I do get username , userToken is also always "0x0000000000000000".
,secDesc is also alwys null.
Did my setup missing something or is there any other method to implement so I can check  whic folder / report user is requesting
![image](https://user-images.githubusercontent.com/4448913/59359885-7789a700-8d2f-11e9-8eb7-9190b51bf001.png)

**Comment by gboreki** [comment]
The username and usertoken should match what was provided by your Authentication Extension. The securityDescriptor should be the one your authorization extension returned when CreateSecurityDescriptor was called. So I suggest placing breakpoints there to see the flow, that would be called when the item is created and provided during check access. Note that since the authorization model for ssrs allows for inheritance, you will not have one per item (they would by default just inherit from the parents permissions).

**Comment by adopilot** [comment]
@gboreki  > CreateSecurityDescriptor 
I do not why but I cant get event to hit break point in CreateSecurityDescriptor .
When I did set permissions for user on Report Portal now I am getting secDesc in requests.
Do I need manually to call CreateSecurityDescriptor or it does report server.

**Comment by adopilot** [comment]
Apologies for spamming
Looks like I figured how it is works.
Can someone please confirm am I understanding thins correct:

methods CheckAccess receiving params   secDesc and username.
secDesc param holds permissions set on SSRS item (eg report, folder, datasource).
in CheckAccess methods we need to check does username parameter maching in secDesc.
If secDrescrpion contains macing username with matching requierd operation metho retun true for autorization?

**Comment by vpratti** [comment]
@adopilot I am in the same boat as you were. I can't seem to hit the CreateSecurityDescriptor. How did you solve it? Can you please share.
