### ISSUE TITLE
SSRS2016 : Redirect URL is not working

### ISSUE THREAD

**Issue by spvignesh** [microsoft/Reporting-Services#163]
Hi,

I'm using SSRS 2016. When i try to hit my report pages directly without logging in then it will direct me to the login page, after logging in instead of redirecting to the report page (ie FormsAuthentication.RedirectFromLoginPage()) it opens the "/ReportServer" page.

ie. **Expected Url :** /ReportServer/Pages/ReportViewer.aspx?%2fReports%2fDashBoard&rs:Command=Render

**Actual Url:** /ReportServer

I have tried SSRS2017 version, it worked fine in that environment but only in SSRS2016 i'm facing this issue.
I don't want the user to navigate to the report page manually, i want to show the report page directly once the user is logged in.
Let me know a possible solution to handle this.

Thanks in advance.

**Comment by drc2100** [comment]
try use "/ReportServer" instead of "/Reports" for URLROOT configuration.

**Comment by gboreki** [comment]
There was a hotfix issued for 2016 to correct some issues with redirect paths, are you running the latest available ServicePack? If you still see this issue after installing the latest service pack you would need to contact Microsoft Support to request for a hotfix in that version. If upgrading is an option for you I'd suggest to upgrade to ssrs 2017 or ssrs 2019 where this problem was addressed.

Thanks
-Boreki
