### ISSUE TITLE
Embed without authentication

### ISSUE THREAD

**Issue by gugoan** [microsoft/Reporting-Services#186]
Hello,

I am trying to incorporate a report on the company's intranet page, but I would like no authentication to be requested.

I tried the way below (pass login by parameter in the url) that I saw in a post but it didn't work. Is there any way to do it?

`<iframe src="http://myusername@mypassword:MyServerRport/relatorios/powerbi/Inteligencia/Cashback?rs:embed=true" width="100%" height="800" frameborder="0"></iframe>`

**Versions used:**

- Microsoft Power BI Report Server (May 2020)
- SQL SERVER 2019 Developer Edition (15.2002.4709.1) (Both in PT-BR)

**Comment by jtarquino** [comment]
You will need to implement your own custom security extension with anonymous Auth (A sample is available https://github.com/microsoft/Reporting-Services/tree/master/CustomSecuritySample)

**Comment by Soheil65** [comment]
totally it doesn't work on iframe when use IP instead of  localhost, for example 
It doesn't work --> <iframe style="width:1000px;height:800px;" src="http://172.16.0.58:8088/Reports/powerbi/Parameter?rs:embed=true"   ></iframe>

It works fine --> <iframe style="width:1000px;height:800px;" src="http://localhost:8088/Reports/powerbi/Parameter?rs:embed=true"   ></iframe>
