### ISSUE TITLE
sample database code issue

### ISSUE THREAD

**Issue by figuerres** [Microsoft/Reporting-Services#20]
this sample has code that grants permsssions to 'NT AUTHORITY\NETWORK SERVICE'

but on a windows 10 developer pc that is not the account that the reporting services uses so the database can not be opened.
readme and sample code should discus what account is used and how to handle the virtual service accounts used by sql server 2016

**Comment by bdwakefield** [comment]
By default I think installing it on Server uses a Virtual Service Account as well. I think this is just how SQL/SSRS works now?

We changed ours to use Network Service although we had a machine that was using a local account as well that we ended up scrapping because our custom version of the auth extension wasn't working and I wanted to start clean with the sample code as-is; which we got working.

It would be nice to get some real clarification on what accounts should be used.

**Comment by figuerres** [comment]
@bdwakefield  i think you are right about the accounts used.
also in my case i saw so many problems that i made a web site in web forms to run reports using the web forms control. then i made the web forms site use a JWT / OAuth token.
so now we have to manage creating a number of server local users who are granted rights on reports and mapping the users to roles  but that seems to be a better option than going into ssrs auth code at this time.
but still this is a mess created by the assumption that  the only users are AD users and that the user rights should be handled as an NT ACL.
SSRS V Next should remove that and make the users, user auth and user roles not depend on Windows and AD , it's a web app and should use extensible api's for that stuff.

**Comment by jtarquino** [comment]
The samples are general guidelines, we welcome and encourage contributions , feel free to send a pull request with proposed changes to make the instructions more clear
