### ISSUE TITLE
can not start reporting service configuration manager

### ISSUE THREAD

**Issue by jwalawic** [microsoft/Reporting-Services#200]
After changes all three config files for custom authentication. Now can not start reporting service configuration manger, giving invalid class() error. Also can not start reporting service from services as well.

**Comment by jtarquino** [comment]
I recommend to do a configuration in a clean environment with the [automated script ](https://docs.microsoft.com/en-us/previous-versions/aspnet/mt152016(v=vs.113)) and compare side by side the configuration changes in order to identify what could be different with your implementation.

Also please check in the log files for additional information about the failure

**Comment by jwalawic** [comment]
which automated script are you referring? This link showing something else. I have MS SQL Reporting Service 2017 and changes all three config files in report server but now can not start reporting service at all. Is there a way we can chat or talk?
