### ISSUE TITLE
How to use IntPtr to reference ClaimsIdentity

### ISSUE THREAD

**Issue by rposener** [Microsoft/Reporting-Services#79]
Hello,

Thanks for the great examples here.  This has been enormously helpful.  I do have 1 concern in my code that is not clear how this should be handled from any of the examples.  In my IAuthenticationExtension2 I set the identity to a ClaimsPrincipal, complete with roles.  However, in the IAuthorizationExtension we only get passed in the username.  

I've done something which I'm quite certain is creating a Memory Leak - I'm using GCHandle to get a reference to the ClaimsIdentity as an IntPtr and returning that for the out.  This allows me to access it in the Authorization, so I can check for Roles the user is in to verify Permissions and Check Access.

However, as I'm creating a new reference every time and never cleaning those up and GC will not touch those.  Is there something I'm missing or should do differently?  Guess I'm a bit stumped about how to properly share those details between the 2 different interfaces.

**Comment by rposener** [comment]
Just a quick follow up - [this](https://github.com/PracticeEngine/SSRS.Security/blob/master/src/SSRS2016.OpenIDConnect.Security/SSRSAuthentication.cs#L20) is what I have done on my IAuthenticationExtension2 which creates an Identity after authenticating via Open Id Connect provider.  Basically I create Identities and store them in a ConcurrentDictionary, along with a sliding timeout.  Then I have a timer running that periodically checks for Identities that we need to cleanup.  Once the timeout happens it calls Free() on a Handle in order to let GC clean it up.  Not sure it's the best way - but does seem to work fine.  I will continue to work on improving it.

**Comment by figuerres** [comment]
@rposener  wow, it looks like i am going to follow your code, i am looking to use my Identity Server V3 STS and it looks like you are doing much the same thing .....   if you have any tips or details please share them!

**Comment by rposener** [comment]
@figuerres - we've been running that code internally for a little while and haven't run into issues yet.  I can't say it's 100% cleanest code - the somewhat arbitrary cleanupTimer (as opposed to a session End event or something) and the static list of Identities are probably not ideal.  But it is working well from our use so far.  Can't say we've put into a larger environment yet - if you find other spots for improvement would love to see what you come up with so we can all benefit until MS offers a better solution.

Cheers.

**Comment by figuerres** [comment]
@rposener thanks for the info.

i am going  over where i took the MS sample code and started trying to work out how to do this,
then  found your code.

so i am patching in some of your code to my code to see if i get it to work.

it looks like sometime today or tomorrow i can start to test my version.
i have taken some calls you had in your pe utility and moved them to the OIDC class so that my app helper only has the get roles and validate  bits.
when i get the first tests working then i can start to see how it all works out.
when i started to look at this i was seeing all the id server sample code using the startup.cs to add support but with SSRS we can't do that, you appear to have dealt with that  which is great.
